name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main
      - master

      

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v4  # Updated to latest version
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3  # Updated to latest version
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_CRED }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5  # Updated to latest version
        with:
          context: .  # Fixed typo from 'content' to 'context'
          file: ./Dockerfile
          push: true
          tags: |
            boyinfuture/ci-cd-testing:latest
            boyinfuture/ci-cd-testing:${{ github.sha }}  # Added SHA tag for versioning
      
      - name: Verify Pushed Image
        run: docker pull boyinfuture/ci-cd-testing:latest